# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'jarvis.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Alis_Face(object):
    def setupUi(self, Alis_Face):
        Alis_Face.setObjectName("Alis_Face")
        Alis_Face.resize(1170, 600)
        self.centralwidget = QtWidgets.QWidget(Alis_Face)
        self.centralwidget.setObjectName("centralwidget")
        self.bg_1 = QtWidgets.QLabel(self.centralwidget)
        self.bg_1.setGeometry(QtCore.QRect(-30, -150, 1201, 901))
        self.bg_1.setText("")
        self.bg_1.setPixmap(QtGui.QPixmap("..//G.U.I Material//B.G//Black_Template.jpg"))
        self.bg_1.setObjectName("bg_1")
        self.bg_2 = QtWidgets.QLabel(self.centralwidget)
        self.bg_2.setGeometry(QtCore.QRect(10, 10, 441, 301))
        self.bg_2.setStyleSheet("background-color: rgb(10, 14, 255);")
        self.bg_2.setText("")
        self.bg_2.setObjectName("bg_2")
        self.Gif_1 = QtWidgets.QLabel(self.centralwidget)
        self.Gif_1.setGeometry(QtCore.QRect(20, 20, 421, 281))
        self.Gif_1.setText("")
        self.Gif_1.setPixmap(QtGui.QPixmap("..//G.U.I Material//B.G//Iron_Template_1.gif"))
        self.Gif_1.setScaledContents(True)
        self.Gif_1.setObjectName("Gif_1")
        self.bg_3 = QtWidgets.QLabel(self.centralwidget)
        self.bg_3.setGeometry(QtCore.QRect(460, 10, 441, 301))
        self.bg_3.setStyleSheet("background-color: rgb(10, 14, 255);")
        self.bg_3.setText("")
        self.bg_3.setObjectName("bg_3")
        self.Gif_2 = QtWidgets.QLabel(self.centralwidget)
        self.Gif_2.setGeometry(QtCore.QRect(470, 20, 421, 281))
        self.Gif_2.setText("")
        self.Gif_2.setPixmap(QtGui.QPixmap("..//G.U.I Material//ExtraGui//Hero_Template.gif"))
        self.Gif_2.setScaledContents(True)
        self.Gif_2.setObjectName("Gif_2")
        self.Gif_3 = QtWidgets.QLabel(self.centralwidget)
        self.Gif_3.setGeometry(QtCore.QRect(-180, 140, 801, 611))
        self.Gif_3.setText("")
        self.Gif_3.setPixmap(QtGui.QPixmap("..//G.U.I Material//VoiceReg//Siri_1.gif"))
        self.Gif_3.setScaledContents(True)
        self.Gif_3.setObjectName("Gif_3")
        self.bg_4 = QtWidgets.QLabel(self.centralwidget)
        self.bg_4.setGeometry(QtCore.QRect(910, 10, 241, 191))
        self.bg_4.setStyleSheet("background-color: rgb(10, 14, 255);")
        self.bg_4.setText("")
        self.bg_4.setObjectName("bg_4")
        self.Gif_4 = QtWidgets.QLabel(self.centralwidget)
        self.Gif_4.setGeometry(QtCore.QRect(920, 20, 221, 171))
        self.Gif_4.setText("")
        self.Gif_4.setPixmap(QtGui.QPixmap("..//G.U.I Material//ExtraGui//Earth.gif"))
        self.Gif_4.setScaledContents(True)
        self.Gif_4.setObjectName("Gif_4")
        self.bg_5 = QtWidgets.QLabel(self.centralwidget)
        self.bg_5.setGeometry(QtCore.QRect(390, 330, 761, 261))
        self.bg_5.setText("")
        self.bg_5.setPixmap(QtGui.QPixmap("..//G.U.I Material//B.G//gyhf.jpg"))
        self.bg_5.setScaledContents(True)
        self.bg_5.setObjectName("bg_5")
        self.text_Jarvis = QtWidgets.QTextBrowser(self.centralwidget)
        self.text_Jarvis.setGeometry(QtCore.QRect(480, 490, 581, 71))
        self.text_Jarvis.setStyleSheet("background-color: Transparent;\n"
"border-redius:none;")
        self.text_Jarvis.setObjectName("text_Jarvis")
        self.text_You = QtWidgets.QTextBrowser(self.centralwidget)
        self.text_You.setGeometry(QtCore.QRect(480, 360, 581, 71))
        self.text_You.setStyleSheet("background-color: Transparent;\n"
"border-redius:none;")
        self.text_You.setObjectName("text_You")
        self.pushbotton_start = QtWidgets.QPushButton(self.centralwidget)
        self.pushbotton_start.setGeometry(QtCore.QRect(930, 220, 201, 41))
        self.pushbotton_start.setStyleSheet("background-color: rgb(0, 0, 0);\n"
"color: rgb(0, 255, 255);\n"
"font: 28pt \"Nyala\";\n"
"border-redius:none;")
        self.pushbotton_start.setObjectName("pushbotton_start")
        self.bg_6 = QtWidgets.QLabel(self.centralwidget)
        self.bg_6.setGeometry(QtCore.QRect(910, 210, 241, 111))
        self.bg_6.setStyleSheet("background-color: rgb(10, 14, 255);")
        self.bg_6.setText("")
        self.bg_6.setObjectName("bg_6")
        self.pushbotton_Exit = QtWidgets.QPushButton(self.centralwidget)
        self.pushbotton_Exit.setGeometry(QtCore.QRect(930, 270, 201, 41))
        self.pushbotton_Exit.setStyleSheet("background-color: rgb(0, 0, 0);\n"
"color: rgb(0, 255, 255);\n"
"font: 28pt \"Nyala\";\n"
"border-redius:none;")
        self.pushbotton_Exit.setObjectName("pushbotton_Exit")
        self.bg_1.raise_()
        self.Gif_3.raise_()
        self.bg_2.raise_()
        self.Gif_1.raise_()
        self.bg_3.raise_()
        self.Gif_2.raise_()
        self.bg_4.raise_()
        self.Gif_4.raise_()
        self.bg_5.raise_()
        self.text_Jarvis.raise_()
        self.text_You.raise_()
        self.bg_6.raise_()
        self.pushbotton_start.raise_()
        self.pushbotton_Exit.raise_()
        Alis_Face.setCentralWidget(self.centralwidget)

        self.retranslateUi(Alis_Face)
        QtCore.QMetaObject.connectSlotsByName(Alis_Face)

    def retranslateUi(self, Alis_Face):
        _translate = QtCore.QCoreApplication.translate
        Alis_Face.setWindowTitle(_translate("Alis_Face", "MainWindow"))
        self.pushbotton_start.setText(_translate("Alis_Face", "Start"))
        self.pushbotton_Exit.setText(_translate("Alis_Face", "Exit"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Alis_Face = QtWidgets.QMainWindow()
    ui = Ui_Alis_Face()
    ui.setupUi(Alis_Face)
    Alis_Face.show()
    sys.exit(app.exec_())
